# Generated by Django 5.0.14 on 2026-08-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComisionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('monto_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentaje_aplicado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monto_comision', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Comisión de venta',
                'verbose_name_plural': 'Comisiones de venta',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('SUSCRIPCION', 'Suscripción'), ('COMISION', 'Comisión')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periodo_desde', models.DateField(blank=True, null=True)),
                ('periodo_hasta', models.DateField(blank=True, null=True)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('VENCIDA', 'Vencida')], default='PENDIENTE', max_length=20)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='Referido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado')], default='PENDIENTE', max_length=20)),
                ('beneficio_aplicado', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Referido',
                'verbose_name_plural': 'Referidos',
            },
        ),
    ]
