# Generated by Django 5.0.14 on 2026-08-25 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturacion', '0001_initial'),
        ('pedidos', '0001_initial'),
        ('suscripciones', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comisionventa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='usuarios.empresa'),
        ),
        migrations.AddField(
            model_name='comisionventa',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='factura',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='usuarios.empresa'),
        ),
        migrations.AddField(
            model_name='factura',
            name='suscripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='suscripciones.suscripcion'),
        ),
        migrations.AddField(
            model_name='comisionventa',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comisiones', to='facturacion.factura'),
        ),
        migrations.AddField(
            model_name='referido',
            name='empresa_referente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referidos_hechos', to='usuarios.empresa'),
        ),
        migrations.AddField(
            model_name='referido',
            name='empresa_referida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referidos_recibidos', to='usuarios.empresa'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['empresa'], name='facturacion_empresa_55c080_idx'),
        ),
        migrations.AddConstraint(
            model_name='factura',
            constraint=models.CheckConstraint(check=models.Q(('monto__gte', 0)), name='factura_monto_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='referido',
            constraint=models.CheckConstraint(check=models.Q(('empresa_referente', models.F('empresa_referida')), _negated=True), name='referido_empresas_distintas'),
        ),
    ]
