# Generated by Django 5.0.14 on 2026-08-28 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_initial'),
        ('usuarios', '0003_rol_superadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('QR', 'Código QR'), ('CUENTA_BANCARIA', 'Cuenta bancaria'), ('PASARELA', 'Pasarela de pago')], max_length=20)),
                ('nombre', models.CharField(help_text='Ej: "QR BCP", "Cuenta Banco Unión", "Stripe"', max_length=100)),
                ('banco', models.CharField(blank=True, max_length=100)),
                ('numero_cuenta', models.CharField(blank=True, max_length=50)),
                ('titular', models.CharField(blank=True, max_length=150)),
                ('imagen_qr', models.ImageField(blank=True, null=True, upload_to='metodos_pago/')),
                ('proveedor_pasarela', models.CharField(blank=True, help_text='Ej: Stripe, PagoFácil', max_length=100)),
                ('referencia_pasarela', models.CharField(blank=True, help_text='ID de cuenta/comercio en la pasarela (no credenciales secretas)', max_length=150)),
                ('predeterminado', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='usuarios.empresa')),
            ],
            options={
                'verbose_name': 'Método de pago',
                'verbose_name_plural': 'Métodos de pago',
                'indexes': [models.Index(fields=['empresa'], name='facturacion_empresa_0425b1_idx')],
            },
        ),
    ]
