# Generated by Django 5.0.14 on 2026-08-25 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_initial'),
        ('inventario', '0002_initial'),
        ('pedidos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='comprador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to='usuarios.comprador'),
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.carrito'),
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalogo.producto'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='comprador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='usuarios.comprador'),
        ),
        migrations.AddField(
            model_name='pago',
            name='orden_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='pedidos.ordencompra'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_envio', to='usuarios.direccion'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='usuarios.empresa'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='orden_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='pedidos.ordencompra'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='sucursal_recojo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_recojo', to='inventario.sucursal'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='pedido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrega', to='pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalogo.producto'),
        ),
        migrations.AddConstraint(
            model_name='carritoitem',
            constraint=models.CheckConstraint(check=models.Q(('cantidad__gt', 0)), name='carrito_item_cantidad_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='ordencompra',
            constraint=models.CheckConstraint(check=models.Q(('monto_total__gte', 0)), name='orden_monto_total_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(check=models.Q(('monto__gte', 0)), name='pago_monto_gte_0'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['empresa'], name='pedidos_ped_empresa_3e0f64_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['orden_compra'], name='pedidos_ped_orden_c_22d5aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(check=models.Q(('subtotal__gte', 0)), name='pedido_subtotal_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('modalidad_entrega', 'RECOJO_TIENDA'), ('sucursal_recojo__isnull', False)), models.Q(('direccion_envio__isnull', False), ('modalidad_entrega', 'ENVIO_DOMICILIO')), _connector='OR'), name='pedido_modalidad_entrega_consistente'),
        ),
        migrations.AddConstraint(
            model_name='pedidoitem',
            constraint=models.CheckConstraint(check=models.Q(('cantidad__gt', 0)), name='pedido_item_cantidad_gt_0'),
        ),
    ]
