# Generated by Django 5.0.14 on 2026-08-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_entrega_funciones_y_triggers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='metodo_pago',
            field=models.CharField(choices=[('TARJETA', 'Tarjeta'), ('QR', 'QR'), ('PAYPAL', 'PayPal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('TARJETA', 'Tarjeta'), ('QR', 'QR'), ('PAYPAL', 'PayPal')], max_length=20),
        ),
    ]
