# Generated by Django 5.0.14 on 2026-08-28 23:35

import apps.comunicacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmensaje',
            name='archivo',
            field=models.FileField(blank=True, null=True, storage=apps.comunicacion.models._chat_media_storage, upload_to='chat/'),
        ),
        migrations.AlterField(
            model_name='chatmensaje',
            name='contenido',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='chatmensaje',
            name='tipo',
            field=models.CharField(choices=[('TEXTO', 'Texto'), ('IMAGEN', 'Imagen'), ('AUDIO', 'Audio'), ('VIDEO', 'Video')], default='TEXTO', max_length=20),
        ),
    ]
