# Generated by Django 5.0.14 on 2026-08-28 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0004_funciones_y_triggers'),
        ('usuarios', '0008_empresa_bloqueo_live_hasta'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotinteraccion',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interacciones_chatbot', to='usuarios.empresa'),
        ),
        migrations.CreateModel(
            name='ChatbotFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('palabras_clave', models.CharField(help_text='Palabras separadas por coma que activan esta respuesta (ej: "horario, hora, abierto")', max_length=255)),
                ('pregunta_ejemplo', models.CharField(blank=True, max_length=200)),
                ('respuesta', models.TextField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='usuarios.empresa')),
            ],
            options={
                'verbose_name': 'Pregunta frecuente del chatbot',
                'verbose_name_plural': 'Preguntas frecuentes del chatbot',
                'indexes': [models.Index(fields=['empresa'], name='comunicacio_empresa_49bfb5_idx')],
            },
        ),
    ]
