# Generated by Django 5.0.14 on 2026-08-25 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='creado_por_empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_creados', to='usuarios.empleado'),
        ),
        migrations.AddField(
            model_name='producto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='usuarios.empresa'),
        ),
        migrations.AddField(
            model_name='categorizacionialog',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorizaciones_ia', to='catalogo.producto'),
        ),
        migrations.AddField(
            model_name='productoimagen',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='catalogo.producto'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['empresa'], name='catalogo_pr_empresa_972c8b_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria'], name='catalogo_pr_categor_8a569f_idx'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(check=models.Q(('precio__gte', 0)), name='producto_precio_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(check=models.Q(('precio_descuento__isnull', True), ('precio_descuento__gte', 0), _connector='OR'), name='producto_precio_descuento_gte_0'),
        ),
    ]
