# Generated by Django 5.0.14 on 2026-08-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_auditoria_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoimagen',
            name='archivo',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='productoimagen',
            name='url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
