# Generated by Django 5.0.14 on 2026-08-25 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveCommerceSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=150)),
                ('url_stream', models.URLField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('EN_VIVO', 'En vivo'), ('FINALIZADA', 'Finalizada')], default='PROGRAMADA', max_length=20)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sesión de live commerce',
                'verbose_name_plural': 'Sesiones de live commerce',
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('PORCENTAJE', 'Porcentaje'), ('MONTO_FIJO', 'Monto fijo')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=20)),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
            },
        ),
        migrations.CreateModel(
            name='PromocionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Producto en promoción',
                'verbose_name_plural': 'Productos en promoción',
            },
        ),
        migrations.CreateModel(
            name='LiveCommerceProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Producto en sesión live',
                'verbose_name_plural': 'Productos en sesión live',
            },
        ),
    ]
