# Generated by Django 5.0.14 on 2026-08-25 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_initial'),
        ('promociones', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livecommercesesion',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='usuarios.empresa'),
        ),
        migrations.AddField(
            model_name='livecommercesesion',
            name='productos',
            field=models.ManyToManyField(related_name='sesiones_live', through='promociones.LiveCommerceProducto', to='catalogo.producto'),
        ),
        migrations.AddField(
            model_name='livecommerceproducto',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promociones.livecommercesesion'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='usuarios.empresa'),
        ),
        migrations.AddField(
            model_name='promocionproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto'),
        ),
        migrations.AddField(
            model_name='promocionproducto',
            name='promocion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promociones.promocion'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='productos',
            field=models.ManyToManyField(related_name='promociones', through='promociones.PromocionProducto', to='catalogo.producto'),
        ),
        migrations.AlterUniqueTogether(
            name='livecommerceproducto',
            unique_together={('sesion', 'producto')},
        ),
        migrations.AlterUniqueTogether(
            name='promocionproducto',
            unique_together={('promocion', 'producto')},
        ),
        migrations.AddConstraint(
            model_name='promocion',
            constraint=models.CheckConstraint(check=models.Q(('valor__gt', 0)), name='promocion_valor_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='promocion',
            constraint=models.CheckConstraint(check=models.Q(('fecha_fin__gt', models.F('fecha_inicio'))), name='promocion_fechas_validas'),
        ),
    ]
