# Generated by Django 5.0.14 on 2026-08-29 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0004_live_funciones_y_triggers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioLive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('texto', models.CharField(max_length=280)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='promociones.livecommercesesion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentario de live',
                'verbose_name_plural': 'Comentarios de live',
                'indexes': [models.Index(fields=['sesion'], name='promociones_sesion__40d610_idx')],
            },
        ),
    ]
