# Generated by Django 5.0.14 on 2026-08-29 05:19

import apps.promociones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0006_comentariolive_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='livecommercesesion',
            name='grabacion',
            field=models.FileField(blank=True, null=True, storage=apps.promociones.models._grabacion_live_storage, upload_to='lives/grabaciones/'),
        ),
        migrations.AddField(
            model_name='livecommercesesion',
            name='pausado_desde',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
