# Generated by Django 5.0.14 on 2026-08-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=50)),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limite_productos', models.PositiveIntegerField(blank=True, null=True)),
                ('incluye_live_commerce', models.BooleanField(default=False)),
                ('incluye_ia', models.BooleanField(default=False)),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('VENCIDA', 'Vencida'), ('SUSPENDIDA', 'Suspendida'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=20)),
                ('renovacion_automatica', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
            },
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(check=models.Q(('precio_mensual__gte', 0)), name='plan_precio_mensual_gte_0'),
        ),
    ]
