# Generated by Django 5.0.14 on 2026-09-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0004_plan_funciones_y_triggers'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='codigo',
            field=models.CharField(blank=True, help_text='CU01: identidad estable para los planes de autoservicio (PRUEBA/BASICO/PREMIUM). Vacío para planes de catálogo que el SuperAdmin arma a mano.', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='duracion_dias',
            field=models.PositiveIntegerField(default=30, help_text='CU01: cuántos días dura la suscripción al comprar este plan.'),
        ),
    ]
