# Generated by Django 5.0.14 on 2026-09-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0006_seed_planes_autoservicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='fecha_inicio',
            field=models.DateTimeField(help_text='CU01: fecha y hora exactas de adquisición del plan.'),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='fecha_vencimiento',
            field=models.DateTimeField(help_text='CU01: fecha y hora exactas de vencimiento del plan.'),
        ),
    ]
