# Generated by Django 5.0.14 on 2026-08-28 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_permiso_gestionar_facturacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='referida_por',
            field=models.ForeignKey(blank=True, help_text='CU27: empresa cuyo código de referido se usó al registrarse.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referidas', to='usuarios.empresa'),
        ),
        migrations.AddField(
            model_name='solicitudempresa',
            name='codigo_referido',
            field=models.CharField(blank=True, help_text='CU27: slug de la empresa que lo invitó, si se registró con un código de referido.', max_length=80),
        ),
    ]
