# Generated by Django 5.0.14 on 2026-08-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_empresa_referida_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='bloqueo_live_hasta',
            field=models.DateTimeField(blank=True, help_text='CU17: si está en el futuro, la empresa no puede emitir en vivo (sanción por incumplimiento).', null=True),
        ),
    ]
