# Generated by Django 5.0.14 on 2026-09-07 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0005_plan_codigo_plan_duracion_dias'),
        ('usuarios', '0008_empresa_bloqueo_live_hasta'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudempresa',
            name='paypal_order_id',
            field=models.CharField(blank=True, help_text='CU01: orden de PayPal abierta para pagar un plan Básico/Premium (vacío para el plan Prueba).', max_length=50),
        ),
        migrations.AddField(
            model_name='solicitudempresa',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='CU01: plan elegido al solicitar. Nulo solo en solicitudes viejas, previas a esta funcionalidad.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_empresa', to='suscripciones.plan'),
        ),
    ]
