# Generated by Django 5.0.14 on 2026-09-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_solicitudempresa_paypal_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='correo_recuperacion',
            field=models.EmailField(blank=True, max_length=150),
        ),
    ]
