# Generated by Django 5.0.14 on 2026-08-25 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_initial'),
        ('pedidos', '0002_initial'),
        ('reportes', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacionia',
            name='comprador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='usuarios.comprador'),
        ),
        migrations.AddField(
            model_name='recomendacionia',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='catalogo.producto'),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='comprador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='usuarios.comprador'),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='usuarios.empresa'),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='pedido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='valoracion', to='pedidos.pedido'),
        ),
        migrations.AddConstraint(
            model_name='valoracion',
            constraint=models.CheckConstraint(check=models.Q(('calificacion__gte', 1), ('calificacion__lte', 5)), name='valoracion_calificacion_rango'),
        ),
    ]
