# Generated by Django 5.0.14 on 2026-08-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('accion', models.CharField(max_length=100)),
                ('entidad_afectada', models.CharField(blank=True, max_length=50)),
                ('entidad_id', models.BigIntegerField(blank=True, null=True)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Log de auditoría',
                'verbose_name_plural': 'Logs de auditoría',
                'ordering': ['-creado_en'],
            },
        ),
    ]
